### ISSUE TITLE
服务端首次启动失败

### ISSUE THREAD

**Issue by 615303619** [Loli-Server/LoliServer#323]
**Minecraft Version(我的世界版本) :1.16.5

**LoliServer buildVersion(构建版本) :LoliServer-1.16.5-b3d757c-server

**Operating System(操作系统) Windows （jdk11）

**Logs :没有log文件（服务端无法启动） 

**Mod list(模组列表) :无

**Plugin list(插件列表) :无

**Description of issue(描述) :无法启动并出现一下报错内容：
Exception in thread "Keep-Alive-Timer" [21:47:56][错误]: 在试图运行LoliServer时发生异常, 你需要把错误提交给LoliServer开发组
java.lang.OutOfMemoryError: Java heap space
	at java.base/sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at moe.loliserver.legacy.util.InstallUtils.run(InstallUtils.java:119)
	at moe.loliserver.legacy.util.InstallUtils.startInstallation(InstallUtils.java:76)
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by Kotori0629** [comment]
OutOfMemory

**Comment by srlss123** [comment]
其实就是内存超了 推荐小白别开服(
作者震惊！

**Comment by 615303619** [comment]
噗哈哈哈哈哈哈不好意思，我不小心把启动脚本的G写成M了（英语不好的屑），填麻烦了啊哈，抱歉
