### ISSUE TITLE
[1.16]Buckets from other mods don't work

### ISSUE THREAD

**Issue by Sleepwalkerx** [Loli-Server/LoliServer#325]
Minecraft Version -> 1.16.5
LoliServer buildVersion -> 1.16.5-b3d757c

Operating System -> Windows

Concerned mod / plugin -> any bucket mod. Plugins are not used

Logs Error When I use the bucket :

```
[15:15:33][Server thread][FATAL]: Error executing task on Server
[15:15:33][Server thread][WARN]: java.lang.NullPointerException
[15:15:33][Server thread][WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:365)
[15:15:33][Server thread][WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:355)
[15:15:33][Server thread][WARN]:        at net.minecraft.item.BucketItem.func_180616_a(BucketItem.java:129)
[15:15:33][Server thread][WARN]:        at WoodenBuckets.Items.WoodenBucketItem.func_77659_a(WoodenBucketItem.java:109)
[15:15:33][Server thread][WARN]:        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:385)
[15:15:33][Server thread][WARN]:        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:353)
[15:15:33][Server thread][WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:1473)
[15:15:33][Server thread][WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:30)
[15:15:33][Server thread][WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:9)
[15:15:33][Server thread][WARN]:        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22)
[15:15:33][Server thread][WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[15:15:33][Server thread][WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[15:15:33][Server thread][WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[15:15:33][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:871)
[15:15:33][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:171)
[15:15:33][Server thread][WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[15:15:33][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:854)
[15:15:33][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:848)
[15:15:33][Server thread][WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97)
[15:15:33][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:833)
[15:15:33][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:766)
[15:15:33][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264)
[15:15:33][Server thread][WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
```

Steps to Reproduce:
 1. I take a bucket of any liquid in my hand. Moreover, this bucket is not from the minecraft mod (but the liquid is).
 2. I try to pour it on the ground and get the following error

Description of issue :
I've checked and it works with any mod that adds its own buckets to the game. I get this error every time I try to pour out the liquid. In the example, I used a mod for wooden buckets, which adds a bucket with: lava, water and milk. But I can't pour out either lava or water, the liquid immediately disappears, and an error goes to the console.

**Comment by Kotori0629** [comment]
Tell me what's other mods bucket, give me mod

**Comment by XionioXMaster** [comment]
> Tell me what's other mods bucket, give me mod

woodbucket 
https://www.curseforge.com/minecraft/mc-mods/wooden-buckets

**Comment by Sleepwalkerx** [comment]
> Tell me what's other mods bucket, give me mod

woodbucket  -> https://www.curseforge.com/minecraft/mc-mods/wooden-buckets
