### ISSUE TITLE
[1.16] TrChat(修复版)无法使用

### ISSUE THREAD

**Issue by yuyuko233** [Loli-Server/LoliServer#332]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "[LoliServer-1.16.5-9e46bd3-server.jar](https://github.com/Loli-Server/LoliServer/actions/runs/1788321689)"

**Operating System(操作系统) :** Windows 10 21H2

**Concerned mod / plugin(有关的插件/Mod) :** [TrChat(修复版)](https://github.com/FlickerProjects/TrChat) 最新构建([[1.90-R6] Fix #68](https://github.com/FlickerProjects/TrChat/actions/runs/1787901588))

**Logs :** 
[TrChat(修复版)的issue](https://github.com/FlickerProjects/TrChat/issues/69)
玩家进出服务器的报错:
https://pastebin.com/yMMUdDPs
下面是插件启动时的报错
```
[15:35:28][Server thread][INFO]: [TrChat] Enabling TrChat v1.90-R6
[15:35:28][Server thread][INFO]: [PlaceholderAPI] Successfully registered expansion: trchat [1.90-R6]
[15:35:28][Server thread][ERROR]: Error occurred while enabling TrChat v1.90-R6 (Is it up to date?)
java.lang.NoClassDefFoundError: org/slf4j/spi/SLF4JServiceProvider
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:576) ~[?:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265) ~[?:?]
        at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300) ~[?:?]
        at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385) ~[?:?]
        at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104) ~[?:?]
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147) ~[?:?]
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139) ~[?:?]
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421) ~[?:?]
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407) ~[?:?]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356) ~[?:?]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382) ~[?:?]
        at com.zaxxer.hikari_4_0_3.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource(Database.kt:18) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource$default(Database.kt:17) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource(Host.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource$default(Host.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.Database.<init>(Database.kt:5) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupPlayerDatabase(DatabaseHandler.kt:31) ~[?:?]
        at me.arasple.mc.trchat.internal.data.Database.init(Database.kt:31) ~[?:?]
        at me.arasple.mc.trchat.TrChat.onEnable(TrChat.kt:67) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:412) ~[forge:1.16.5-ccb19cf]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:323) ~[forge:1.16.5-ccb19cf]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:426) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:344) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:724) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.SLF4JServiceProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 46 more
[15:35:28][Server thread][INFO]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2482
```

**Steps to Reproduce(复现步骤) :**
 1. 启动服务器
 2. 进入服务器
 3. 发消息

**Description of issue :** 
 在spigot1.16.5上无问题
启动的时候还缺少SLF4J

**Comment by Kotori0629** [comment]
建议让作者尝试同时兼容org.apache.logging.slf4j   不过我还是会尝试修复的

**Comment by yuyuko233** [comment]
> 建议让作者尝试同时兼容org.apache.logging.slf4j 不过我还是会尝试修复的

好的

**Comment by yuyuko233** [comment]
> 建议让作者尝试同时兼容org.apache.logging.slf4j 不过我还是会尝试修复的

那玩家进入服务器, 发送消息报错也是这个问题吗?

**Comment by Kotori0629** [comment]
> > 建议让作者尝试同时兼容org.apache.logging.slf4j 不过我还是会尝试修复的
> 
> 那玩家进入服务器, 发送消息报错也是这个问题吗?

一个一个来 不急

**Comment by yuyuko233** [comment]
好的, 麻烦作者了

**Comment by Kotori0629** [comment]
![Y${N7RJ IWSMAB69J1(QPY](https://user-images.githubusercontent.com/81866089/152536037-13261cad-07d3-4f00-a4c8-f24446806aec.png)
好了
