### ISSUE TITLE
[1.16] CoreProtect NoClassDefFoundError

### ISSUE THREAD

**Issue by Dev4lexG** [Loli-Server/LoliServer#355]
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-b90f47b-server.jar"

**Concerned mod / plugin(有关的插件/Mod) :** CoreProtect

**Logs :** 
```
[16:27:38][Server thread][ERROR]: Could not pass event HangingBreakEvent to CoreProtect v21.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[forge:?]
        at net.minecraft.entity.item.HangingEntity.func_70071_h_(HangingEntity.java:125) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:755) ~[?:?]
        at net.minecraft.world.World.func_217390_a(World.java:814) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:528) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1019) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:929) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:762) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bukkit.craftbukkit.v1_16_R3.CraftArt
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPainting.getArt(CraftPainting.java:23) ~[forge:?]
        at net.coreprotect.listener.entity.HangingBreakListener.onHangingBreak(HangingBreakListener.java:72) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
        ... 13 more
```

**Steps to Reproduce(复现步骤) :**
 1. idk

**Comment by Kotori0629** [comment]
Cannot repeat
