### ISSUE TITLE
[1.16] Error message with bungee network

### ISSUE THREAD

**Issue by Dev4lexG** [Loli-Server/LoliServer#358]
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-1e51f20-server.jar (latest)"

**Concerned software) :** Waterfall-Loliserver

**Logs :**
```
[18:23:06][Server thread][FATAL]: Error executing task on Server
[18:23:06][Server thread][WARN]: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: legacy:LoliServerBungee
[18:23:06][Server thread][WARN]:        at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38)
[18:23:06][Server thread][WARN]:        at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:43)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.fml.network.FMLMCRegisterPacketHandler$ChannelList.bytesToResLocation(FMLMCRegisterPacketHandler.java:78)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.fml.network.FMLMCRegisterPacketHandler$ChannelList.updateFrom(FMLMCRegisterPacketHandler.java:49)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.fml.network.FMLMCRegisterPacketHandler.registerListener(FMLMCRegisterPacketHandler.java:92)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91)
[18:23:06][Server thread][WARN]:        at java.base/java.util.Optional.map(Optional.java:265)
[18:23:06][Server thread][WARN]:        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91)
[18:23:06][Server thread][WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2613)
[18:23:06][Server thread][WARN]:        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42)
[18:23:06][Server thread][WARN]:        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12)
[18:23:06][Server thread][WARN]:        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22)
[18:23:06][Server thread][WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[18:23:06][Server thread][WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[18:23:06][Server thread][WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[18:23:06][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:871)
[18:23:06][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:171)
[18:23:06][Server thread][WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[18:23:06][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:854)
[18:23:06][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:848)
[18:23:06][Server thread][WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97)
[18:23:06][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:833)
[18:23:06][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:766)
[18:23:06][Server thread][WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264)
[18:23:06][Server thread][WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Steps to Reproduce(复现步骤) :**
 1. Setup Waterfall proxy
 2. Configure Loliserver for work with bungeecord
 3. Join in the server

**I can give you permissions for easy-test the error on the pterodactyl pannel. Send me md for give you log-in details**

**Comment by Kotori0629** [comment]
LoliServer cannot work with all bungee proxy
