### ISSUE TITLE
无法使用trchat

### ISSUE THREAD

**Issue by srlss123** [Loli-Server/LoliServer#37]
[02:43:46] [Server thread/WARN]:        at java.util.zip.ZipFile.open(Native Method)
[02:43:46] [Server thread/WARN]:        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[02:43:46] [Server thread/WARN]:        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[02:43:46] [Server thread/WARN]:        at java.util.jar.JarFile.<init>(JarFile.java:166)
[02:43:46] [Server thread/WARN]:        at java.util.jar.JarFile.<init>(JarFile.java:130)
[02:43:46] [Server thread/WARN]:        at me.arasple.mc.trchat.boot.Plugin.getPluginDescription(Plugin.java:332)
[02:43:46] [Server thread/WARN]:        at me.arasple.mc.trchat.boot.Plugin.checkLibPlugin(Plugin.java:363)
[02:43:46] [Server thread/WARN]:        at me.arasple.mc.trchat.boot.Plugin.init(Plugin.java:447)
[02:43:46] [Server thread/WARN]:        at me.arasple.mc.trchat.boot.Plugin.<clinit>(Plugin.java:161)
[02:43:46] [Server thread/WARN]:        at java.lang.Class.forName0(Native Method)
[02:43:46] [Server thread/WARN]:        at java.lang.Class.forName(Class.java:348)
[02:43:46] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:89)
[02:43:46] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[02:43:46] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[02:43:46] [Server thread/WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[02:43:46] [Server thread/WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[02:43:46] [Server thread/WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[02:43:46] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:43:46] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160)
[02:43:46] [Server thread/INFO]: [TabooLib] 当前由 TrChat 引导主运行库启动.
[02:43:46] [Server thread/WARN]: java.lang.NoSuchFieldException: ucp
[02:43:46] [Server thread/WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[02:43:46] [Server thread/WARN]:        at moe.loliserver.remapper.proxy.ProxyReflection.getDeclaredField(ProxyReflection.java:61)
[02:43:46] [Server thread/WARN]:        at me.arasple.mc.trchat.boot.Plugin$Loader.addPath(Plugin.java:736)
[02:43:46] [Server thread/WARN]:        at me.arasple.mc.trchat.boot.Plugin.init(Plugin.java:461)
[02:43:46] [Server thread/WARN]:        at me.arasple.mc.trchat.boot.Plugin.<clinit>(Plugin.java:161)
[02:43:46] [Server thread/WARN]:        at java.lang.Class.forName0(Native Method)
[02:43:46] [Server thread/WARN]:        at java.lang.Class.forName(Class.java:348)
[02:43:46] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:89)
[02:43:46] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[02:43:46] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[02:43:46] [Server thread/WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[02:43:46] [Server thread/WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[02:43:46] [Server thread/WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[02:43:46] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:43:46] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160)
[02:43:46] [Server thread/INFO]: [TabooLib] 主运行库未完成初始化, 插件停止加载.

**Comment by srlss123** [comment]
插件列表 AdvancedBan, AT, BossCooling, CMI, CMILib, ConsoleSpamFix, CoreProtect, GroupManagerLP, LiteSignIn, LuckPerms, MiaoChat, MiniMOTD, Multiverse-Core, PlaceholderAPI, PlugMan, ProtocolLib, TAB, TradePlus, TradeSystem, TrChat, Vault

**Comment by srlss123** [comment]
03:02:20] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[03:02:22] [Server thread/WARN]: Legacy plugin BossCooling v1.19 does not specify an api-version.
[03:02:23] [Server thread/WARN]: java.lang.NoSuchFieldException: ucp
[03:02:23] [Server thread/WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[03:02:23] [Server thread/WARN]:        at moe.loliserver.remapper.proxy.ProxyReflection.getDeclaredField(ProxyReflection.java:61)
[03:02:23] [Server thread/WARN]:        at me.arasple.mc.trchat.Plugin$Loader.addPath(Plugin.java:672)
[03:02:23] [Server thread/WARN]:        at me.arasple.mc.trchat.Plugin.init(Plugin.java:396)
[03:02:23] [Server thread/WARN]:        at me.arasple.mc.trchat.Plugin.<clinit>(Plugin.java:148)
[03:02:23] [Server thread/WARN]:        at java.lang.Class.forName0(Native Method)
[03:02:23] [Server thread/WARN]:        at java.lang.Class.forName(Class.java:348)
[03:02:23] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:89)
[03:02:23] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[03:02:23] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[03:02:23] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301)
[03:02:23] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:296)
[03:02:23] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208)
[03:02:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:721)
[03:02:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271)
[03:02:23] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[03:02:23] [Server thread/INFO]: [TabooLib] 主运行库未完成初始化, 插件停止加载.
[03:02:23] [Server thread/WARN]: Legacy plugin NotBoom v1.3 does not specify an api-version.
[03:02:23] [Server thread/WARN]: Legacy plugin GroupManagerLP v1.0 does not specify an api-version.
[03:02:23] [Server thread/WARN]: Legacy plugin AT v1.1-beta(MC1.9) does not specify an api-version.
[03:02:25] [Server thread/WARN]: Legacy plugin TradeSystem vB5-NT does not specify an api-version.
>....[authlib-injector] [INFO] Transformed [me.arasple.mc.trmenu.util.Skulls] with [Constant URL Transformer]
[03:02:32] [Server thread/INFO]: [TabooLib] Forge server detected, TabooLib will be loaded as a plugin.
这个插件不知道为什么会在Taboolib之前加载

**Comment by srlss123** [comment]
然后用plugman重载也提示[TabooLib] 主运行库未完成初始化, 插件停止加载.

**Comment by srlss123** [comment]
去除mcmt 使用java8 /java11均不可以使用
[03:47:11] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[03:47:13] [Server thread/WARN]: Legacy plugin BossCooling v1.19 does not specify an api-version.
[03:47:14] [Server thread/WARN]: java.lang.NoSuchFieldException: ucp
[03:47:14] [Server thread/WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[03:47:14] [Server thread/WARN]:        at moe.loliserver.remapper.proxy.ProxyReflection.getDeclaredField(ProxyReflection.java:61)
[03:47:14] [Server thread/WARN]:        at me.arasple.mc.trchat.Plugin$Loader.addPath(Plugin.java:672)
[03:47:14] [Server thread/WARN]:        at me.arasple.mc.trchat.Plugin.init(Plugin.java:396)
[03:47:14] [Server thread/WARN]:        at me.arasple.mc.trchat.Plugin.<clinit>(Plugin.java:148)
[03:47:14] [Server thread/WARN]:        at java.lang.Class.forName0(Native Method)
[03:47:14] [Server thread/WARN]:        at java.lang.Class.forName(Class.java:348)
[03:47:14] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:89)
[03:47:14] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[03:47:14] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[03:47:14] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301)
[03:47:14] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:296)
[03:47:14] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208)
[03:47:14] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:721)
[03:47:14] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271)
[03:47:14] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[03:47:14] [Server thread/INFO]: [TabooLib] 主运行库未完成初始化, 插件停止加载.
[03:47:14] [Server thread/WARN]: Legacy plugin NotBoom v1.3 does not specify an api-version.
[03:47:14] [Server thread/WARN]: Legacy plugin GroupManagerLP v1.0 does not specify an api-version.
[03:47:14] [Server thread/WARN]: Legacy plugin AT v1.1-beta(MC1.9) does not specify an api-version.
[03:47:15] [Server thread/WARN]: Legacy plugin TradeSystem vB5-NT does not specify an api-version.

**Comment by Kotori0629** [comment]
[TabooLib] 主运行库未完成初始化, 插件停止加载.
