### ISSUE TITLE
模组加载导致sever出错，为1.16.5版本无前置的模组

### ISSUE THREAD

**Issue by wadigzxc** [Loli-Server/LoliServer#373]
C:\Users\Administrator\Desktop\lolisever>"C:\Program Files\Java\jre1.8.0_321\bin\java.exe" -Xms4G -Xmx4G -jar LoliServer-1.16.5-b35e5c7-server.jar
.____          .__  .__  _________
|    |    ____ |  | |__|/   _____/ ______________  __ ___________
|    |   /  _ \|  | |  |\_____  \_/ __ \_  __ \  \/ // __ \_  __ \
|    |__(  <_> )  |_|  |/        \  ___/|  | \/\   /\  ___/|  | \/
|_______ \____/|____/__/_______  /\___  >__|    \_/  \___  >__|
        \/                     \/     \/                 \/
                             Welcome to LoliServer 1.16.5 ! - LoliServer Developement Group

[17:18:15][INFO]: JAVA版本验证完成, LoliServer进程将继续进行
[17:18:16][main][INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.34, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[17:18:16][main][INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_321 by Oracle Corporation
[17:18:17][main][INFO]: Added Lets Encrypt root certificates as additional trust
[17:18:17][main][INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Administrator/Desktop/lolisever/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[17:18:18][main][INFO]: Launching target 'fmlserver' with arguments [--gameDir, .]
[17:18:19][main][INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[17:18:19][main][INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[17:18:19][main][INFO]: [org.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[17:18:28][modloading-worker-2][FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER (It may crash the server, please report it to the mod author)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:72)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.lang.ClassLoader.loadClass(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at com.github.tartaricacid.i18nupdatemod.I18nUpdateMod.<init>(I18nUpdateMod.java:26)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.lang.reflect.Constructor.newInstance(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.lang.Class.newInstance(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[17:18:28][modloading-worker-2][INFO]: [net.minecraftforge.fml.loading.RuntimeDistCleaner:processClassWithFlags:72]:   at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[17:18:28][modloading-worker-3][INFO]: Forge mod loading, version 36.2.34, for MC 1.16.5 with MCP 20210115.111550
[17:18:28][modloading-worker-2][ERROR]: Failed to create mod instance. ModID: i18nupdatemod, class com.github.tartaricacid.i18nupdatemod.I18nUpdateMod
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/IWindowEventListener
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_321]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_321]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at com.github.tartaricacid.i18nupdatemod.I18nUpdateMod.<init>(I18nUpdateMod.java:26) ~[i18nupdatemod:2.0.1]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_321]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_321]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_321]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_321]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_321]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_321]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_321]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_321]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.IWindowEventListener
        at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        ... 19 more
        Suppressed: java.lang.ClassNotFoundException
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.1.3.jar:?]
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_321]
                at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_321]
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?]
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
                at com.github.tartaricacid.i18nupdatemod.I18nUpdateMod.<init>(I18nUpdateMod.java:26) ~[i18nupdatemod:2.0.1]
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_321]
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321]
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321]
                at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_321]
                at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_321]
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2]
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
                at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_321]
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_321]
                at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_321]
                at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_321]
                at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_321]
                at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_321]
[17:18:28][modloading-worker-3][INFO]: MinecraftForge v36.2.34 Initialized
[17:18:29][modloading-worker-3][INFO]: EventDispatcherRegistry initialized
[17:18:29][main][FATAL]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[17:18:29][main][FATAL]: Preparing crash report with UUID c9f9c424-881e-4f7e-8ff8-ddca69b9cf21
[17:18:29][main][INFO]: [net.minecraft.crash.CrashReport:func_85057_a:212]: Negative index in crash report handler (16/18)
[17:18:29][main][FATAL]: Crash report saved to .\crash-reports\crash-2022-04-16_17.18.29-fml.txt
---- Minecraft Crash Report ----
// You're mean.

------------
# Chinese:
// 如果你需要得到LoliServer开发组的帮助, 请通过Discord或者QQ联系我们, 或者:
// Step 1: 提交这个Crashreport中的文本至 https://paste.ubuntu.com
// Step 2: 创建一个新的Issues至LoliServer的Github仓库, 地址: https://github.com/Loli-Server/LoliServer1.16/issues
# English and other:
// If you need to LoliServer Development Group help, Contact us at discord or:
// Step 1: Submit this CrashReport to https://paste.ubuntu.com/
// Step 2: Create a new issues to LoliServer's Github repos, Link: https://github.com/Loli-Server/LoliServer1.16/issues
------------

Time: 22-4-16 下午5:18
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
        at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[LoliServer-1.16.5-b35e5c7-server.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:86) [LoliServer-1.16.5-b35e5c7-server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:83) [LoliServer-1.16.5-b35e5c7-server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:80) [LoliServer-1.16.5-b35e5c7-server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_321] {}
-- MOD i18nupdatemod --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/IWindowEventListener
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_321] {}
                at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_321] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321] {}
                at com.github.tartaricacid.i18nupdatemod.I18nUpdateMod.<init>(I18nUpdateMod.java:26) ~[i18nupdatemod:2.0.1] {re:classloading}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_321] {}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321] {}
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321] {}
                at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_321] {}
                at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_321] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2] {re:classloading}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_321] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_321] {}
                at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_321] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_321] {}
                at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_321] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_321] {}

        Mod File: i18nupdatemod-1.16.5-2.0.1.jar
        Failure message: I18n update Mod (i18nupdatemod) has failed to load correctly
                java.lang.NoClassDefFoundError: net/minecraft/client/renderer/IWindowEventListener
        Mod Version: 2.0.1
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.IWindowEventListener
Stacktrace:
        at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_321] {}
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_321] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321] {}
        at com.github.tartaricacid.i18nupdatemod.I18nUpdateMod.<init>(I18nUpdateMod.java:26) ~[i18nupdatemod:2.0.1] {re:classloading}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_321] {}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321] {}
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_321] {}
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_321] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_321] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_321] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_321] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_321] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_321] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_321] {}

-- System Details --
Details:
        Minecraft Version: 1.16.5
        Minecraft Version ID: 1.16.5
        LoliServer Version: 1.16.5-b35e5c7
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_321, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 3196145184 bytes (3048 MB) / 4161798144 bytes (3969 MB) up to 4161798144 bytes (3969 MB)
        CPUs: 4
        JVM Flags: 2 total; -Xms4G -Xmx4G
        ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
        ModLauncher launch target: fmlserver
        ModLauncher naming: srg
        ModLauncher services:
                /mixin-0.8.4.jar mixin PLUGINSERVICE
                /eventbus-4.0.0.jar eventbus PLUGINSERVICE
                /LoliServer-1.16.5-b35e5c7-server.jar object_holder_definalize PLUGINSERVICE
                /LoliServer-1.16.5-b35e5c7-server.jar runtime_enum_extender PLUGINSERVICE
                /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE
                /LoliServer-1.16.5-b35e5c7-server.jar capability_inject_definalize PLUGINSERVICE
                /LoliServer-1.16.5-b35e5c7-server.jar runtimedistcleaner PLUGINSERVICE
                /mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE
                /LoliServer-1.16.5-b35e5c7-server.jar fml TRANSFORMATIONSERVICE
        FML: 36.2
        Forge: net.minecraftforge:36.2.34
        FML Language Providers:
                javafml@36.2
                minecraft@1
        Mod List:
                forge-1.16.5-36.2.34-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
                forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |CREATE_REG|Manifest: NOSIGNATURE
                i18nupdatemod-1.16.5-2.0.1.jar                    |I18n update Mod               |i18nupdatemod                 |2.0.1               |ERROR     |Manifest: NOSIGNATURE
        Crash Report UUID: c9f9c424-881e-4f7e-8ff8-ddca69b9cf21
        CraftBukkit Information:
   Running:
   Failed to handle CraftCrashReport: craftbukkit not runs
[17:18:29][main][FATAL]: Failed to start the minecraft server

C:\Users\Administrator\Desktop\lolisever>pause
请按任意键继续. . .

**Comment by wadigzxc** [comment]
自动汉化更新mod安装地址：https://github.com/CFPAOrg/I18nUpdateMod2/actions

**Comment by Kotori0629** [comment]
这个mod不需要安装在服务端
