### ISSUE TITLE
无法使用quickshop 开箱子闪退

### ISSUE THREAD

**Issue by srlss123** [Loli-Server/LoliServer#38]
Could not pass event InventoryCloseEvent to QuickShop v4.0.7.6
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1326) ~[forge:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_71053_j(ServerPlayerEntity.java:1292) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:459) ~[?:?]
        at org.jmt.mcmt.asmdest.ASMHookTerminator.lambda$callEntityTick$4(ASMHookTerminator.java:184) ~[jmt_mcmt:0.20.75]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_282]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_282]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_282]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_282]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_282]
Caused by: java.lang.IllegalStateException: Tile is null, asynchronous access? %sCraftBlock{pos=BlockPos{x=-25, y=67, z=-219},type=CHEST,data=Block{minecraft:chest}[facing=east,type=single,waterlogged=false],fluid=net.minecraft.fluid.EmptyFluid@70abd04e}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:27) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.CraftContainer.<init>(CraftContainer.java:13) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.CraftLootable.<init>(CraftLootable.java:16) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.CraftChest.<init>(CraftChest.java:19) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getState(CraftBlock.java:338) ~[forge:?]
        at org.maxgamer.quickshop.shade.io.papermc.lib.features.blockstatesnapshot.BlockStateSnapshotNoOption.getBlockState(BlockStateSnapshotNoOption.java:8) ~[?:?]
        at org.maxgamer.quickshop.shade.io.papermc.lib.environments.Environment.getBlockState(Environment.java:109) ~[?:?]
        at org.maxgamer.quickshop.shade.io.papermc.lib.PaperLib.getBlockState(PaperLib.java:191) ~[?:?]
        at org.maxgamer.quickshop.shop.ShopManager.getShopIncludeAttached_Fast(ShopManager.java:1372) ~[?:?]
        at org.maxgamer.quickshop.shop.ShopManager.getShopIncludeAttached(ShopManager.java:360) ~[?:?]
        at org.maxgamer.quickshop.shop.ShopManager.getShopIncludeAttached(ShopManager.java:343) ~[?:?]
        at org.maxgamer.quickshop.listener.PlayerListener.onInventoryClose(PlayerListener.java:258) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
        ... 12 more

**Comment by srlss123** [comment]
插件列表 AdvancedBan, AT, BossCooling, CMI, CMILib, ConsoleSpamFix, CoreProtect, GroupManagerLP, LiteSignIn, LuckPerms, MiaoChat, MiniMOTD, Multiverse-Core, PlaceholderAPI, PlugMan, ProtocolLib, TAB, TradePlus, TradeSystem, TrChat, Vault
环境 java8 291

**Comment by srlss123** [comment]
插件列表: AdvancedBan, AT, BossCooling, CMI, CMILib, ConsoleSpamFix, CoreProtect, GroupManagerLP, InventoryRollback, LiteSignIn, LuckPerms, MiaoChat, MiniMOTD, Multiverse-Core, NotBoom, PlaceholderAPI, PlugMan, ProtocolLib, QuickShop, Residence, TAB, TabooLib5, TradePlus, TradeSystem, TrChat, TrMenu, Vault, WorldEdit, XConomy
环境:java8_281

**Comment by srlss123** [comment]
实测 Java11正常 已删除mcmt
