### ISSUE TITLE
TrMenu v2.08

### ISSUE THREAD

**Issue by 233littileone** [Loli-Server/LoliServer#41]
[14:54:33] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to TrMenu v2.08
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:451) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:418) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:414) ~[forge:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_175087_a(ServerPlayNetHandler.java:1859) ~[?:?]
        at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:31) ~[?:?]
        at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:9) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:868) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:178) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:851) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:845) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:830) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:763) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException: player.openInventory must not be null
        at me.arasple.mc.trmenu.modules.listener.bukkit.ListenerItemInteract$onInteract$1.run(ListenerItemInteract.kt:30) ~[?:?]
        at me.arasple.mc.trmenu.modules.service.mirror.MirrorData.eval(MirrorData.kt:37) ~[?:?]
        at me.arasple.mc.trmenu.modules.service.mirror.Mirror.eval(Mirror.kt:16) ~[?:?]
        at me.arasple.mc.trmenu.modules.service.mirror.Mirror.eval$default(Mirror.kt:15) ~[?:?]
        at me.arasple.mc.trmenu.modules.listener.bukkit.ListenerItemInteract.onInteract(ListenerItemInteract.kt:25) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
        ... 23 more

**Comment by Kotori0629** [comment]
前置库问题
